# Generated by Django 5.0.7 on 2024-08-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='appname',
            field=models.CharField(default='No App Name', max_length=100),
        ),
        migrations.AddField(
            model_name='login',
            name='note',
            field=models.TextField(default='Nothing Here', max_length=250),
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='No Password', max_length=100),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='No Username', max_length=100),
        ),
    ]
