# Generated by Django 5.0.7 on 2024-08-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_login_user'),
        ('main_app', '0004_alter_login_appname_alter_login_note_and_more'),
    ]

    operations = [
    ]
