# Generated by Django 5.0.7 on 2024-08-08 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_login_appname_alter_login_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='my_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
