# Generated by Django 5.0.7 on 2024-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_login_appname_alter_login_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
