# Generated by Django 5.0.7 on 2024-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_login_my_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
