# Generated by Django 5.0.7 on 2024-08-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_login_my_datetime_alter_login_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='my_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
