# Generated by Django 5.1 on 2024-11-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='appname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
